DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BOARD_COMMENT CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BOARD_NO;
DROP SEQUENCE SEQ_CATEGORY_NO;
DROP SEQUENCE SEQ_BOARD_COMMENT_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_COMMENT_NO NOCACHE NOCYCLE;

CREATE TABLE BOARD
(
    NO NUMBER PRIMARY KEY
    , TITLE VARCHAR2(100)
    , CONTENT VARCHAR2(100)
    , CREATED_AT TIMESTAMP DEFAULT SYSDATE
    , MODIFIED_AT TIMESTAMP
    , HIT NUMBER DEFAULT 0
    , DEL_YN CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN ('Y', 'N'))
    , CATEGORY_NO NUMBER
);

CREATE TABLE CATEGORY
(
    CATEGORY_NO NUMBER PRIMARY KEY
    , CATEGORY_NAME VARCHAR2(100)
);

CREATE TABLE BOARD_COMMENT (
    BOARD_COMMENT_NO NUMBER PRIMARY KEY
    , BOARD_NO NUMBER NOT NULL
    , CONTENT VARCHAR2(500)
    , CREATED_AT TIMESTAMP DEFAULT SYSDATE
    , DEL_YN CHAR(1) DEFAULT 'N' CHECK(DEL_YN IN ('Y', 'N'))
);

ALTER TABLE BOARD ADD CONSTRAINT FK_CATEGORY_TO_BOARD FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY (CATEGORY_NO);
ALTER TABLE BOARD_COMMENT ADD CONSTRAINT FK_BOARD_TO_BOARD_COMMENT FOREIGN KEY (BOARD_NO) REFERENCES BOARD (NO);

INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY_NO.NEXTVAL, '공지');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY_NO.NEXTVAL, '개발');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY_NO.NEXTVAL, '운동');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY_NO.NEXTVAL, '연애');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (SEQ_CATEGORY_NO.NEXTVAL, '자유');

INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '1 번째 게시글', '내용입니다.', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '2 번째 게시글', '두 번째 게시글의 내용입니다.', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '3 번째 게시글', '이 글은 삭제해주십시오.', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '4 번째 게시글', '공지사항 내용입니다.', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '5 번째 게시글', '테스트용 게시글입니다.', 5);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '6 번째 게시글', 'ㅋ', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '7 번째 게시글', 'ㅋㅋ', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '8 번째 게시글', 'ㅋㅋㅋ', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '9 번째 게시글', 'ㅋㅋㅋㅋ', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '10 번째 게시글', 'ㅋㅋㅋㅋㅋ', 5);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '11 번째 게시글', 'ㅋ', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '12 번째 게시글', 'ㅋㅋ', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '13 번째 게시글', 'ㅋㅋㅋ', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '14 번째 게시글', 'ㅋㅋㅋㅋ', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '15 번째 게시글', 'ㅋㅋㅋㅋㅋ', 5);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '16 번째 게시글', 'ㅋ', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '17 번째 게시글', 'ㅋㅋ', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '18 번째 게시글', 'ㅋㅋㅋ', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '19 번째 게시글', 'ㅋㅋㅋㅋ', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '20 번째 게시글', 'ㅋㅋㅋㅋㅋ', 5);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '21 번째 게시글', 'ㅋ', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '22 번째 게시글', 'ㅋㅋ', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '23 번째 게시글', 'ㅋㅋㅋ', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '24 번째 게시글', 'ㅋㅋㅋㅋ', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '25 번째 게시글', 'ㅋㅋㅋㅋㅋ', 5);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '26 번째 게시글', 'ㅋ', 2);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '27 번째 게시글', 'ㅋㅋ', 3);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '28 번째 게시글', 'ㅋㅋㅋ', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '29 번째 게시글', 'ㅋㅋㅋㅋ', 1);
INSERT INTO BOARD (NO, TITLE, CONTENT, CATEGORY_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, '30 번째 게시글', 'ㅋㅋㅋㅋㅋ', 5);

INSERT INTO BOARD_COMMENT (BOARD_COMMENT_NO, BOARD_NO, CONTENT) VALUES (SEQ_BOARD_COMMENT_NO.NEXTVAL, 1, '1 번째 게시글 댓글');
INSERT INTO BOARD_COMMENT (BOARD_COMMENT_NO, BOARD_NO, CONTENT) VALUES (SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, '2 번째 게시글 댓글');
INSERT INTO BOARD_COMMENT (BOARD_COMMENT_NO, BOARD_NO, CONTENT) VALUES (SEQ_BOARD_COMMENT_NO.NEXTVAL, 3, '3 번째 게시글 댓글');
INSERT INTO BOARD_COMMENT (BOARD_COMMENT_NO, BOARD_NO, CONTENT) VALUES (SEQ_BOARD_COMMENT_NO.NEXTVAL, 4, '4 번째 게시글 댓글');
INSERT INTO BOARD_COMMENT (BOARD_COMMENT_NO, BOARD_NO, CONTENT) VALUES (SEQ_BOARD_COMMENT_NO.NEXTVAL, 5, '5 번째 게시글 댓글');

COMMIT;